# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolsBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QVBoxLayout, QLabel, QPushButton, QGridLayout, QScrollArea, QWidget

from framerwork.classes import *

WIDTH = 720
HEIGHT = 600


class ToolItem(QtWidgets.QFrame):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.button = None
        self.toolData = None
        self.initUI()

    def initUI(self):
        self.setFrameShape(QtWidgets.QFrame.Box)
        self.setFixedWidth(150)
        self.setFixedHeight(150)

    def addButton(self, toolData):

        # 创建工具框的内部布局
        tool_layout = QVBoxLayout(self)

        tool_name = QLabel(toolData.getName())
        tool_name.setAlignment(Qt.AlignCenter)

        tool_button = QPushButton("启动")
        tool_button.toolData = toolData
        tool_layout.addWidget(tool_name)
        tool_layout.addWidget(tool_button)
        self.button = tool_button
        # 将内部布局应用于工具框
        self.setLayout(tool_layout)


class Ui_MainWindow(object):

    def __init__(self):
        self.toolsBtnTab = None
        self.statusbar = None
        self.gridLayout = None
        self.scrollAreaWidgetContents = None
        self.scrollArea = None
        self.toolsDir = None
        self.horizontalLayout = None
        self.verticalLayout = None
        self.centralWidget = None
        self.settingButton = None

    def setupUi(self, MainWindow):
        MainWindow.resize(WIDTH, HEIGHT)
        # 保持窗口大小不变
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        self.centralWidget = QtWidgets.QWidget(MainWindow)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.settingButton = QtWidgets.QPushButton(self.centralWidget)
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout.addWidget(self.settingButton)

        self.cacheDir = QtWidgets.QPushButton(self.centralWidget)
        self.cacheDir.setObjectName("cacheDir")
        self.horizontalLayout.addWidget(self.cacheDir)

        self.toolsDir = QtWidgets.QPushButton(self.centralWidget)
        self.toolsDir.setObjectName("toolsDir")
        self.horizontalLayout.addWidget(self.toolsDir)

        self.verticalLayout.addLayout(self.horizontalLayout)

        MainWindow.setCentralWidget(self.centralWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # statusBar显示版本号
        self.statusbar.showMessage("版本号：" + G_VERSION)
        self.translateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showToolsBox(self, data):
        ROW = 4
        # # 创建一个网格布局
        layout = QGridLayout()

        i = 0
        tab = {}
        noShwoTab = DataPool().getData("NoShowTab")

        if noShwoTab is None:
            noShwoTab = {}


        for tool in data:
            getPath = data[tool].getPath()
            # if noShwoTab[getPath] is not None and noShwoTab[getPath]:
            #     continue
            # Log().info(noShwoTab.get(getPath) )

            if noShwoTab.get(getPath) and noShwoTab[getPath]:
                continue
            tool_frame = ToolItem()
            tool_frame.addButton(data[tool])
            # # 将工具框添加到网格布局中
            layout.addWidget(tool_frame, i // ROW, i % ROW)
            tab[tool] = tool_frame.button
            i = i + 1
        self.toolsBtnTab = tab
        scroll_area = QScrollArea()
        widget = QWidget()
        widget.setLayout(layout)
        scroll_area.setWidget(widget)
        scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.verticalLayout.addWidget(scroll_area)

    def translateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(G_PROJECT_NAME)
        self.settingButton.setText(_translate("MainWindow", "设置"))
        self.toolsDir.setText(_translate("MainWindow", "打开工具文件夹"))
        self.cacheDir.setText(_translate("MainWindow", "打开缓存文件夹"))
